#!/usr/bin/env python3
# .env Diffusion - Because manually copying secrets is how we keep them "secure"

import sys
import os
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description='Diffuse .env files like a pro (or a lazy dev)')
    parser.add_argument('source', help='Source .env file')
    parser.add_argument('target', help='Target .env file')
    parser.add_argument('--dry-run', action='store_true', help='Pretend to work, like most meetings')
    parser.add_argument('--force', action='store_true', help='Overwrite like a reckless intern')
    
    args = parser.parse_args()
    
    # Check if source exists (unlike my motivation on Mondays)
    if not Path(args.source).exists():
        print(f"Error: Source file '{args.source}' not found. Did you check the couch?")
        sys.exit(1)
    
    # Read source .env
    with open(args.source, 'r') as f:
        source_lines = f.readlines()
    
    # Filter out comments and empty lines (like filtering out bad ideas)
    source_vars = []
    for line in source_lines:
        line = line.strip()
        if line and not line.startswith('#'):
            source_vars.append(line)
    
    print(f"Found {len(source_vars)} environment variables in source")
    
    # Check if target exists
    target_exists = Path(args.target).exists()
    
    if target_exists and not args.force:
        print(f"Target '{args.target}' exists. Use --force to overwrite (or just YOLO it)")
        sys.exit(1)
    
    if args.dry_run:
        print("Dry run mode: All talk, no action (like corporate strategy)")
        print(f"Would write {len(source_vars)} variables to '{args.target}'")
        print("Sample variables:")
        for var in source_vars[:3]:  # Show first 3
            print(f"  {var}")
        if len(source_vars) > 3:
            print(f"  ... and {len(source_vars) - 3} more secrets to spill")
        return
    
    # Write to target (the actual work part)
    with open(args.target, 'w') as f:
        f.write('# Generated by .env Diffusion - Your secrets are now in 2 places!\n')
        for var in source_vars:
            f.write(f"{var}\n")
    
    print(f"Success! Diffused {len(source_vars)} variables to '{args.target}'")
    print("Remember: With great .env files comes great responsibility (to not commit them)")

if __name__ == '__main__':
    main()